apiVersion: v1
kind: Service
metadata:
  name: fastapi-local-service
  labels:
    app: fastapi-local
spec:
  selector:
    app: fastapi-local
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
